runtime: python37
instance_class: F2
entrypoint: gunicorn -b :8080 -w 2 main:app

env_variables:
          BUCKET_NAME: "<your bucket name>"
          ACCESS_KEY: "<your aws key>"
          SECRET_KEY: "<your aws secret>"
          OPTIMIZER_ACCESS_KEY: "<your aws key>"
          OPTIMIZER_SECRET_KEY: "<your aws secret>"
